version: '3'

services:
  n8n-mcp:
    image: ghcr.io/ctkadvisors/n8n-mcp-memory:main
    # Alternatively, build locally:
    # build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - N8N_API_URL=${N8N_API_URL}
      - N8N_API_KEY=${N8N_API_KEY}
    restart: unless-stopped
    volumes:
      - n8n_mcp_cache:/app/cache

volumes:
  n8n_mcp_cache:
