name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Setup Git hooks
        run: pnpm simple-git-hooks

      - name: Build
        run: pnpm run build

      - name: Run tests with coverage
        run: NODE_OPTIONS="--no-warnings --experimental-vm-modules" pnpm run test src/api/__tests__/n8nClient.test.ts src/services/__tests__/n8nServiceV2.test.ts

      # Temporarily disable coverage upload until all tests are fixed
      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: test-coverage-${{ matrix.node-version }}
      #     path: coverage/
      #     retention-days: 5
