name: Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'src/**/*.ts'
      - '.github/workflows/docs.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create Documentation
        run: |
          # Create docs directory structure
          mkdir -p docs/api

          # Create a simple index.html file
          cat > docs/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <meta http-equiv="refresh" content="0;url=api/">
            <title>n8n Memory Control Panel Documentation</title>
          </head>
          <body>
            <p>If you are not redirected automatically, follow this <a href="api/">link to the documentation</a>.</p>
          </body>
          </html>
          EOF

          # Create API documentation index
          cat > docs/api/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>n8n Memory Control Panel API Documentation</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; max-width: 800px; margin: 0 auto; }
              h1, h2 { color: #333; }
              pre { background: #f4f4f4; padding: 10px; border-radius: 5px; overflow-y: auto; max-height: 400px; }
            </style>
          </head>
          <body>
            <h1>n8n Memory Control Panel API Documentation</h1>
            <p>This is a temporary documentation page. Full API documentation will be available soon.</p>

            <h2>Repository Structure</h2>
            <pre>
          EOF

          # Add TypeScript files to the documentation
          find src -type f -name "*.ts" | sort >> docs/api/index.html

          # Close the HTML file
          cat >> docs/api/index.html << EOF
            </pre>

            <h2>Main Components</h2>
            <ul>
              <li><strong>API Client</strong>: Handles communication with n8n API</li>
              <li><strong>MCP Tools</strong>: Provides high-level tools for managing n8n resources</li>
              <li><strong>Documentation</strong>: Tools for fetching and managing n8n node documentation</li>
            </ul>

            <h2>Getting Started</h2>
            <p>For more information, please refer to the <a href="https://github.com/ctkadvisors/n8n-mcp-memory" target="_blank">GitHub repository</a>.</p>
          </body>
          </html>
          EOF

          # Create .nojekyll file to disable Jekyll processing
          touch docs/.nojekyll

          # List generated files
          echo "Generated documentation structure:"
          find docs -type f | sort

      # Use JamesIves/github-pages-deploy-action for deployment
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true
