name: Documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'src/**/*.ts'
      - '.github/workflows/docs.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate documentation
        run: |
          pnpm add typedoc
          npx typedoc --out docs/api src/ --skipErrorChecking

      # Deploy directly to gh-pages branch
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git reset --hard
          cp -r docs/* .
          rm -rf docs
          touch .nojekyll
          git add .
          git commit -m "Deploy documentation to GitHub Pages"
          git push -f origin gh-pages
